export const TABLES = {
  SERVICES: 'services',
  AVAILABILITY: 'availability',
  APPOINTMENTS: 'appointments',
  DOCUMENTS: 'documents',
  PROFILES: 'profiles',
  FAQ: 'faq',
  NOTIFICATIONS: 'notifications',
};

export const DEFAULT_CLINICS = [
  {
    id: '123',
    name: 'Main Medical Clinic',
    type: 'clinic',
    email: 'info@mainclinic.com',
    phone: '(555) 111-2222',
    address: '123 Medical Plaza, Healthcare City',
    city: 'Healthcare City',
    state: 'HC',
    zipCode: '12345',
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '10:00', close: '14:00' },
      sunday: { open: null, close: null },
    },
    servicesOffered: ['General Checkup', 'Vaccination', 'Minor Surgery'],
    totalDoctors: 5,
    rating: 4.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_DOCTORS = [
  {
    id: '1',
    name: 'Dr. John Smith',
    type: 'doctor',
    email: 'john.smith@clinic.com',
    specialization: 'General Practitioner',
    qualification: 'MD, Board Certified',
    experience: 10,
    clinicId: '123',
    phone: '(555) 123-4567',
    bio: 'Experienced general practitioner with focus on student health.',
    languages: ['English', 'Spanish'],
    consultationFee: 50,
    rating: 4.7,
    totalReviews: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_DATA = {
  services: [
    {
      id: 'medical',
      name: 'Medical Consultation',
      description: 'Professional medical consultation with healthcare provider',
      category: 'Medical',
      duration: 30,
      price: 50,
      icon: 'medkit-outline',
      color: '#3B82F6',
      availability: 'Available',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'dental',
      name: 'Dental Checkup',
      description: 'Oral examination and dental health assessment',
      category: 'Dental',
      duration: 45,
      price: 75,
      icon: 'fitness-outline',
      color: '#10B981',
      availability: 'Available',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'emergency',
      name: 'Emergency Slot',
      description: 'Immediate emergency medical attention',
      category: 'Emergency',
      duration: 15,
      price: 100,
      icon: 'alert-circle-outline',
      color: '#EF4444',
      availability: 'Available',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  faq: [
    {
      id: 'faq_001',
      question: 'How do I book an appointment?',
      answer: 'You can book an appointment through the app by selecting a doctor, choosing your preferred time slot, and confirming the booking.',
      category: 'Booking',
      helpful: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'faq_002',
      question: 'Can I cancel my appointment?',
      answer: 'Yes, you can cancel your appointment up to 24 hours before the scheduled time. Use the My Appointments section to manage your bookings.',
      category: 'Booking',
      helpful: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'faq_003',
      question: 'What documents do I need to upload?',
      answer: 'Depending on your needs, you may need to upload registration certificate, student ID, insurance card, or medical history documents.',
      category: 'Documents',
      helpful: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'faq_004',
      question: 'Is the app free to use?',
      answer: 'Yes, the app is free to download and use. Service fees may apply when booking appointments.',
      category: 'General',
      helpful: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'faq_005',
      question: 'How long does document verification take?',
      answer: 'Document verification typically takes 2-3 business days. You will receive a notification once your documents are reviewed.',
      category: 'Documents',
      helpful: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};
